from enum import Enum

from _typeshed import Incomplete

class Status(Enum):
    unknown = ...
    untested = ...
    executing = ...
    skipped = ...
    passed = ...
    xfailed = ...
    xpassed = ...
    failed = ...
    error = ...
    hook_error = ...
    cleanup_error = ...
    undefined = ...
    pending = ...
    pending_warn = ...
    untested_pending = ...
    untested_undefined = ...

def __getattr__(name: str) -> Incomplete: ...
